In [2]:
import numpy as np

alpha = 0

def check_row_equals(X):
    for i in range(len(X)):
        if abs(sum(X[0]-X[i])) > alpha:
            return False
    return True


A = [[0.5,0.3,0.2],[0.4,0.2,0.4],[0.0,0.3,0.7]]
A = np.array(A)

for i in range(10):
    A = A @ A
    if check_row_equals(A):
        print(i)
        break

A

array([[0.21818182, 0.27272727, 0.50909091],
       [0.21818182, 0.27272727, 0.50909091],
       [0.21818182, 0.27272727, 0.50909091]])

In [91]:
import numpy as np
A = [[0.5,0.5],[0.3,0.7]]
A = np.array(A)

for i in range(10):
    A = A @ A
    if check_row_equals(A):
        print(i)
        break
A

array([[0.375, 0.625],
       [0.375, 0.625]])

In [99]:
def compute_pi(A):
    for i in range(16):
        A = A @ A
        if check_row_equals(A):
            print(i)
            break
    return A[0]

In [5]:
#Forward alg

def forward(A,B,pi,O):
    N = A.shape[0]
    T = len(O)
    alpha = np.zeros((N,T))
    alpha[:,0] = pi * B[:,O[0]]
    print(alpha)
    for t in range(1,T):
        for i in range(N):
            alpha[i,t] = np.sum(alpha[:,t-1]*A[:,i]) * B[i,O[t]]
    return alpha


A = np.array([[0.7,0.3],[0.4,0.6]])
B = np.array([[0.1,0.4, 0.5],[0.7,0.2,0.1]])
pi = np.array([0.6,0.4])
pi
print(A)
print(B)
O = [0,1,0,2]
forward_alphas = forward(A,B,pi,[0,1,0,2])# best is CHCH
# forward_alphas = forward(A,B,pi,[0,1])
print(forward_alphas)
pHHHH = pi[0]*B[0,0]*A[0,0]*B[0,1]*A[0,0]*B[0,0]*A[0,0]*B[0,2]
pHHHC = pi[0]*B[0,0]*A[0,0]*B[0,1]*A[0,0]*B[0,0]*A[0,1]*B[1,2]
pHHCH = pi[0]*B[0,0]*A[0,0]*B[0,1]*A[0,1]*B[1,0]*A[1,0]*B[0,2]
pHCHH = pi[0]*B[0,0]*A[0,1]*B[1,1]*A[1,0]*B[0,0]*A[0,0]*B[0,2]
# pHHCC = 0.6*0.1*0.7*0.4*0.3*0.7*0.6*0.1
pHHCC = pi[0]*B[0,0]*A[0,0]*B[0,1]*A[0,1]*B[1,0]*A[1,1]*B[1,2]

pHHHH, pHHHC, pHHCH, pHCHH, pHHCC


[[0.7 0.3]
 [0.4 0.6]]
[[0.1 0.4 0.5]
 [0.7 0.2 0.1]]
[[0.06 0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
[[0.06      0.0616    0.0058    0.007742 ]
 [0.28      0.0372    0.02856   0.0018876]]


(0.0004116,
 3.5279999999999994e-05,
 0.0007055999999999999,
 5.04e-05,
 0.00021167999999999995)

[[0.06 0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]


In [160]:
alpha1 = pi * B[:,0]
sekwencja = [0,1,0,2] #SMSL
alpha1_H = pi[0] * B[0,0]
alpha1_C = pi[1] * B[1,0]
print(alpha1_H)
print(alpha1_C)
print(alpha1)

# alpha2_0 = alpha1_0 * A[0,0]*B[0,0] + alpha1_1 * A[1,0]*B[1,0] #0->1
# alpha2_1 = alpha1_0 * A[1,1]*B[0,0] + alpha1_1 * A[0,1]*B[1,0] #0->1
# alpha2_0, alpha2_1

#Przebieg FA dla sekwencji 0,1,0,2 dla CCCH
#dla 0->1
#P(HH)
alpha2_HH = alpha1_H * A[0,0] * B[0,1]
print(alpha2_HH)
#P(HC)
alpha2_CC = alpha1_C * A[1,1] * B[1,1]
print(alpha2_CC)

#dla 0->1->0
alpha3_CCC = alpha2_CC * A[1,1] * B[1,0]
print(alpha3_CCC)

#dla 0->1->0->2
alpha3_CCCH = alpha3_CCC * A[1,0] * B[0,2]
print(alpha3_CCCH)


0.06
0.27999999999999997
[0.06 0.28]
0.0168
0.0336
0.014111999999999998
0.0028223999999999996


In [16]:
def forward_alg_HMM_best(A,B,O):
    alpha0 = pi * B[:,O[0]]
    alpha0 = alpha0.reshape(2,-1)
    print(alpha0)
    sekwence = []
    for t in range(1, len(O)):
        X = A * alpha0 * B[:, O[t]]
        X = np.array(X)
        max_val = np.max(X)
        ind = np.where(X == max_val)
        print(f"max value is for indexes: {ind}")
        if sekwence == []:
            sekwence.append(mapIndexToState(ind[0]))
            print(f"max value for state: {mapIndexToState(ind[0])}{mapIndexToState(ind[1])}")
        else:
            print(f"max value for state: {mapIndexToState(ind[1])}")
        sekwence.append(mapIndexToState(ind[1]))
        alpha0[:,0] = max_val
        print(alpha0)
    return "".join(sekwence)

def forward_alg_DP_best(A,B,O):
    alpha0 = pi * B[:,O[0]]
    alpha0 = alpha0.reshape(2,-1)
    print(alpha0)
    sekwence = []
    for t in range(1, len(O)):
        X = A * alpha0 * B[:, O[t]]
        X = np.array(X)
        max_val = np.max(X, axis=1)
        print(max_val)
        # ind1 = np.where(X == max_val[0])
        # ind2 = np.where(X == max_val[2])
        # print(f"max value is for indexes: {ind}")
        # # print(f"max value for state: {mapIndexToState(ind[0])}{mapIndexToState(ind[1])}")
        # if sekwence == []:
        #     sekwence.append(mapIndexToState(ind[0]))
        #     print(f"max value for state: {mapIndexToState(ind[0])}{mapIndexToState(ind[1])}")
        # else:
        #     print(f"max value for state: {mapIndexToState(ind[1])}")

        sekwence.append(mapIndexToState(ind[1]))
        alpha0[:,0] = max_val
        print(alpha0)
    return "".join(sekwence)

def mapIndexToState(index):
    if index == 0:
        return 'H'
    else:
        return 'C'


print(A)
print(B)
print(pi)
# forward_alg_HMM_best(A,B,[0,1,0,2])
forward_alg_DP_best(A,B,[1,2,2])

[[0.7 0.3]
 [0.4 0.6]]
[[0.1 0.4 0.5]
 [0.7 0.2 0.1]]
[0.6 0.4]
[[0.24]
 [0.08]]
[0.084 0.016]


NameError: name 'ind' is not defined

In [119]:
A = np.array([[0.5,0.5],[0.3,0.7]])
B = np.array([[0.8,0.2],[0.4,0.6]])
pi = compute_pi(A)
alpha1 =  pi * B
print(alpha1)

alpha1_0 = pi[0]*B[0,0]
alpha1_1 = pi[1]*B[1,1]
alpha1_0, alpha1_1

[[0.3   0.125]
 [0.15  0.375]]


(0.29999999999924337, 0.37499999999905403)

# ZADANIA HMM

In [3]:
import numpy as np
A = np.array([[0.6,0.4],[0.3,0.7]])
B = np.array([[0.1,0.4,0.5],[0.7,0.2,0.1]])
pi = np.array([0.7,0.3])

In [56]:
# Problem 1
O = [1,2,0]
alpha_0 = pi * B[:,O[0]]
print(alpha_0)
p_HHH = alpha_0[0] * A[0,0] * B[0,O[1]] * A[0,0] * B[0,O[2]]
p_HHS = alpha_0[0] * A[0,0] * B[0,O[1]] * A[0,1] * B[1,O[2]]
p_HSH = alpha_0[0] * A[0,1] * B[1,O[1]] * A[1,0] * B[0,O[2]]
p_HSS = alpha_0[0] * A[0,1] * B[1,O[1]] * A[1,1] * B[1,O[2]]
p_SSS = alpha_0[1] * A[1,1] * B[1,O[1]] * A[1,1] * B[1,O[2]]
p_SSH = alpha_0[1] * A[1,0] * B[0,O[1]] * A[0,0] * B[0,O[2]]
p_SHS = alpha_0[1] * A[1,0] * B[0,O[1]] * A[0,1] * B[1,O[2]]
p_SHH = alpha_0[1] * A[1,0] * B[0,O[1]] * A[0,0] * B[0,O[2]]
p_HHH, p_HHS, p_HSH, p_HSS, p_SSS, p_SSH, p_SHS, p_SHH
# sekvence_prob = np.sum([p_HHH, p_HHS, p_HSH, p_HSS, p_SSS, p_SSH, p_SHS, p_SHH])
# sekvence_prob
# print(f"{sekvence_prob:.4}")
# P(S) or P(H)
# p_s = p_SSS + p_SSH + p_SHS + p_SHH
# p_h = p_HHH + p_HHS + p_HSH + p_HSS
# p_s, p_h
# results = np.zeros((2,3))
# results[:,0] = [p_h,p_s]
# results
# p_xh = p_HHH + p_HHS + p_SHH + p_SHS
# p_xs = p_SSS + p_SSH + p_HSS + p_HSH
# results[:,1] = [p_xh,p_xs]
# results
# p_xxH = p_HHH + p_SHH + p_HSH + p_SSH
# p_xxS = p_HHS + p_SHS + p_HSS + p_SSS
# results[:,2] = [p_xxH,p_xxS]
# results

[0.28 0.06]


(0.005039999999999999,
 0.023519999999999996,
 0.000336,
 0.005488,
 0.0020579999999999995,
 0.00054,
 0.0025199999999999997,
 0.00054)

In [68]:
def problem_1_forward(A,B,pi,O):
    alpha = np.zeros((2,len(O)))
    alpha[:,0] = pi * B[:,O[0]]
    print(alpha)
    for t in range(1,len(O)):
        for i in range(2):
            alpha[i,t] = np.sum(alpha[:,t-1] * A[:,i]) * B[i,O[t]]
    return alpha


print(O)
result = problem_1_forward(A,B,pi,O)
print(result)
print(result[:,-1])
print(f"{np.sum(result[:,-1]):.4}")

[0, 1, 0, 2]
[[0.06 0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
[[0.06      0.0616    0.0058    0.007742 ]
 [0.28      0.0372    0.02856   0.0018876]]
[0.007742  0.0018876]
0.00963


In [24]:
alphaH_1 = (alpha_0[0] * A[0,0] + alpha_0[1] * A[1,0]) * B[0,2]
alphaH_1

0.09299999999999999

In [25]:
#Viterbi - graf jako drzewo
alfa0_H_1 = pi[0] * B[0,1]
alfa0_S_1 = pi[1] * B[1,1]
alfa0_H_1, alfa0_S_1

(0.27999999999999997, 0.06)

In [8]:
def vitterbi_forward(A,B,pi,O):
    alpha = np.zeros((2,len(O)))
    alpha[:,0] = pi * B[:,O[0]]
    alpha_val = np.max(alpha)
    alpha[alpha != alpha_val] = 0
    for t in range(1,len(O)):
        for i in range(2):
            print(alpha)
            alpha[i,t] = np.sum(alpha[i,t-1] * A[:,i]) * B[i,O[t]]
        alpha_val = np.max(alpha[:,t])
        print(alpha_val)
        # alpha_col= alpha[:,t]
        # alpha_col[alpha_col != alpha_val] = 0
        # alpha[:,t] = alpha_col
    return alpha

O = (1,2,2)
print(vitterbi_forward(A,B,pi,O))
# print(problem_1_forward(A,B,pi,O))
# p_hhh = 0.7*0.4*0.6*0.5*0.6*0.4
# p_hhh
# p_hhs = 0.7*0.4*0.6*0.5*0.4*0.2
# p_hhh, p_hhs
pp = 0.7*0.4*0.6*0.5*0.6*0.4
print(pp)


[[0.24 0.   0.  ]
 [0.   0.   0.  ]]
[[0.24  0.132 0.   ]
 [0.    0.    0.   ]]
0.132
[[0.24  0.132 0.   ]
 [0.    0.    0.   ]]
[[0.24   0.132  0.0726]
 [0.     0.     0.    ]]
0.0726
[[0.24   0.132  0.0726]
 [0.     0.     0.    ]]
0.020159999999999997


In [79]:
print(vitterbi_forward(A,B,pi,O))


[[0.   0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
[[0.     0.0448 0.     0.    ]
 [0.28   0.     0.     0.    ]]
0.27999999999999997
[[0.   0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
[[0.   0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
0.27999999999999997
[[0.   0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
[[0.   0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
0.27999999999999997
[[0.   0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]


In [76]:
#Forward alg

def forward(A,B,pi,O):
    N = A.shape[0]
    T = len(O)
    alpha = np.zeros((N,T))
    alpha[:,0] = pi * B[:,O[0]]
    print(alpha)
    for t in range(1,T):
        for i in range(N):
            alpha[i,t] = np.sum(alpha[:,t-1]*A[:,i]) * B[i,O[t]]
    return alpha


A = np.array([[0.7,0.3],[0.4,0.6]])
B = np.array([[0.1,0.4, 0.5],[0.7,0.2,0.1]])
pi = np.array([0.6,0.4])
pi
print(A)
print(B)
forward_alphas = forward(A,B,pi,[0,1,0,2])# best is CHCH
# forward_alphas = forward(A,B,pi,[0,1])
print(forward_alphas)
pHHHH = pi[0]*B[0,0]*A[0,0]*B[0,1]*A[0,0]*B[0,0]*A[0,0]*B[0,2]
pHHHC = pi[0]*B[0,0]*A[0,0]*B[0,1]*A[0,0]*B[0,0]*A[0,1]*B[1,2]
pHHCH = pi[0]*B[0,0]*A[0,0]*B[0,1]*A[0,1]*B[1,0]*A[1,0]*B[0,2]
pHCHH = pi[0]*B[0,0]*A[0,1]*B[1,1]*A[1,0]*B[0,0]*A[0,0]*B[0,2]
# pHHCC = 0.6*0.1*0.7*0.4*0.3*0.7*0.6*0.1
pHHCC = pi[0]*B[0,0]*A[0,0]*B[0,1]*A[0,1]*B[1,0]*A[1,1]*B[1,2]

pHHHH, pHHHC, pHHCH, pHCHH, pHHCC


[[0.7 0.3]
 [0.4 0.6]]
[[0.1 0.4 0.5]
 [0.7 0.2 0.1]]
[[0.06 0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
[[0.06      0.0616    0.0058    0.007742 ]
 [0.28      0.0372    0.02856   0.0018876]]


(0.0004116,
 3.5279999999999994e-05,
 0.0007055999999999999,
 5.04e-05,
 0.00021167999999999995)

In [83]:
result = problem_1_forward(A,B,pi,[0,1,0,2])
print(result)
print(result[:,-1])
print(f"{np.sum(result[:,-1]):.4}")

[[0.06 0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
[[0.06      0.0616    0.0058    0.007742 ]
 [0.28      0.0372    0.02856   0.0018876]]
[0.007742  0.0018876]
0.00963


In [11]:
import numpy as np
A = np.array([[0.6,0.4],[0.3,0.7]])
B = np.array([[0.1,0.4, 0.5],[0.7,0.2,0.1]])
pi = np.array([0.7,0.3])
O = [1,2,0]
alpha_0_H = pi[0] * B[0][O[0]]
alpha_0_C = pi[1] * B[1][O[0]]
alpha_0_H, alpha_0_C

(0.27999999999999997, 0.06)

In [19]:
alpha_1_H = (alpha_0_H * A[0][0] * B[0][O[1]]) + (alpha_0_C * A[1][0] * B[0][O[1]])
alpha_1_C = (alpha_0_H * A[0][1] * B[1][O[1]]) + (alpha_0_C * A[1][1] * B[1][O[1]])
alpha_1_H, alpha_1_C

alpha_2_H = (alpha_1_H * A[0][0] + alpha_1_C * A[1][0]) * B[0][O[2]]
alpha_2_C = (alpha_1_H * A[0][1] + alpha_1_C * A[1][1]) * B[1][O[2]]
alpha_2_H, alpha_2_C

sum = alpha_2_H + alpha_2_C
print(f"{sum:.4}")


0.03963


In [13]:
p_HHH = alpha_0_H * A[0][0] * B[0][O[1]] * A[0][0] * B[0][O[2]]
p_HHS = alpha_0_H * A[0][0] * B[0][O[1]] * A[0][1] * B[1][O[2]]
p_HSH = alpha_0_H * A[0][1] * B[1][O[1]] * A[1][0] * B[0][O[2]]
p_HSS = alpha_0_H * A[0][1] * B[1][O[1]] * A[1][1] * B[1][O[2]]
p_SSS = alpha_0_C * A[1][1] * B[1][O[1]] * A[1][1] * B[1][O[2]]
p_SSH = alpha_0_C * A[1][1] * B[1][O[1]] * A[1][0] * B[0][O[2]]
p_SHS = alpha_0_C * A[1][0] * B[0][O[1]] * A[0][1] * B[1][O[2]]
p_SHH = alpha_0_C * A[1][0] * B[0][O[1]] * A[0][0] * B[0][O[2]]
p_HHH, p_HHS, p_HSH, p_HSS, p_SSS, p_SSH, p_SHS, p_SHH

sum = p_HHH + p_HHS + p_HSH + p_HSS + p_SSS + p_SSH + p_SHS + p_SHH
print(f"{sum:.4}")

0.03963
